export const defaultCategories = [
  { value: "books", label: "Books", icon: "book" },
  { value: "car", label: "Car", icon: "car" },
  {
    value: "cleaning",
    label: "Cleaning",
    icon: "broom",
    variation: "MaterialCommunityIcons",
  },
  { value: "cloths", label: "Cloths", icon: "skin" },
  {
    value: "credits",
    label: "Credits",
    icon: "bank",
    variation: "MaterialCommunityIcons",
  },
  { value: "electricity", label: "Electricity", icon: "bulb1" },
  { value: "etf's", label: "Etf's", icon: "linechart" },
  { value: "gas", label: "Gas", icon: "dashboard" },
  { value: "general", label: "General", icon: "setting" },
  { value: "gifts", label: "Gifts", icon: "gift" },
  { value: "groceries", label: "Groceries", icon: "shoppingcart" },
  { value: "health", label: "Health", icon: "hearto" },
  { value: "house", label: "House", icon: "home" },
  { value: "management", label: "Management", icon: "calculator" },
  { value: "pets", label: "Pets", icon: "pets", variation: "materialIcons" },
  {
    value: "restaurants",
    label: "Restaurants",
    icon: "dinner-dining",
    variation: "materialIcons",
  },
  {
    value: "transports",
    label: "Transports",
    icon: "airplanemode-active",
    variation: "materialIcons",
  },
  { value: "sports", label: "Sports", icon: "dribbble" },
  { value: "stocks", label: "Stocks", icon: "barchart" },
  { value: "taxes", label: "Taxes", icon: "form" },
  { value: "travel", label: "Travel", icon: "earth" },
  {
    value: "water",
    label: "Water",
    icons: "water",
    variation: "materialIcons",
  },
];

export const defaultIncomesCategories = [
  {
    value: "allowence",
    label: "Allowence",
    variation: "materialIcons",
    icon: "attach-money",
  },
  { value: "freelance", label: "Freelance", icon: "codepen" },
  { value: "general", label: "General", icon: "setting" },
  { value: "guests", label: "Guests", icon: "home" },
  { value: "management", label: "Management", icon: "calculator" },
  { value: "salary", label: "Salary", icon: "work", variant: "materialIcons" },
  { value: "taxes", label: "Taxes", icon: "form" },
];
