export const defaultCategories = [
  { value: "books", label: "Books" },
  { value: "car", label: "Car" },
  { value: "cleaning", label: "Cleaning" },
  { value: "electricity", label: "Electricity" },
  { value: "etf's", label: "Etf's" },
  { value: "general", label: "General" },
  { value: "gifts", label: "Gifts" },
  { value: "groceries", label: "Groceries" },
  { value: "health", label: "Health" },
  { value: "house", label: "House" },
  { value: "management", label: "Management" },
  { value: "pets", label: "Pets" },
  { value: "restaurants", label: "Restaurants" },
  { value: "transports", label: "Transports" },
  { value: "sports", label: "Sports" },
  { value: "stocks", label: "Stocks" },
  { value: "taxes", label: "Taxes" },
  { value: "travel", label: "Travel" },
  { value: "water", label: "Water" },
];

export const defaultIncomesCategories = [
  { value: "allowence", label: "Allowence" },
  { value: "freelance", label: "Freelance" },
  { value: "general", label: "General" },
  { value: "guests", label: "Guests" },
  { value: "management", label: "Management" },
  { value: "salary", label: "Salary" },
  { value: "taxes", label: "Taxes" },
];
