export const queryKeys = {
  businesses: "businesses",
  businessesInvestmentParcels: "businesses-investment-parcels",
  reports: "reports",
  deposits: "deposits",
  realEstate: "real-estate",
  realEstateImages: "real-estate-images-list",
  realEstateImage: "real-estate-image",
  credits: "credits",
  user: "user",
  userSession: "userSession",
  expenses: "expenses",
  monthExpenses: "monthExpenses",
  incomes: "incomes",
  monthIncomes: "monthIncomes",
  watches: "watches",
  cars: "cars",
};
